model_path = "TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T"
freeze_layers = []
attn_implementation = "flash_attention_2"
save_final_training_state = false
context_len = 4096
supports_reasoning = false
supports_tool_calls = false

chat_template = "{% for message in messages %}{% if message['role'] == 'user' %}{{ '<|user|>\n' + message['content'] + eos_token }}{% elif message['role'] == 'system' %}{{ '<|system|>\n' + message['content'] + eos_token }}{% elif message['role'] == 'assistant' %}{{ '<|assistant|>\n' + message['content'] + eos_token }}{% endif %}{% if loop.last and add_generation_prompt %}{{ '<|assistant|>' }}{% endif %}{% endfor %}"
